name: VMAuctions
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: R4KT\AuctionHouse
version: 3.0.0
author: VMPE Development Team
website: Not showing.
commands:
  ah:
    description: "Auction house hub command."
    aliases: ["auction", "auctionhouse"]
